USE [zad4]
GO

DROP TABLE IF EXISTS OSOBA;
GO

DROP TABLE IF EXISTS MIEJSCE_PRACY;
GO

CREATE TABLE [dbo].[OSOBA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NOT NULL,
	[ID_MIEJSCE_PRACY] [int] NOT NULL,
CONSTRAINT [PK_OSOBA] PRIMARY KEY CLUSTERED
([ID] ASC)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[MIEJSCE_PRACY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Opis] [nvarchar](150) NOT NULL,
	CONSTRAINT [PK_MIEJSCE_PRACY] PRIMARY KEY CLUSTERED
([ID] ASC)
) ON [PRIMARY]

ALTER TABLE [dbo].[OSOBA] WITH CHECK ADD CONSTRAINT
[FK_OSOBA_MIEJSCE_PRACY] FOREIGN KEY([ID_MIEJSCE_PRACY])
REFERENCES [dbo].[MIEJSCE_PRACY] ([ID])
