USE [zad5]
GO

DROP TABLE IF EXISTS AUX;
GO
DROP TABLE IF EXISTS OSOBA;
GO
DROP TABLE IF EXISTS MIEJSCE_PRACY;
GO

CREATE TABLE [dbo].[AUX](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_1] [int] NOT NULL,
	[ID_2] [int] NOT NULL,
CONSTRAINT [PK_AUX] PRIMARY KEY CLUSTERED
([ID] ASC))

CREATE TABLE [dbo].[OSOBA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
CONSTRAINT [PK_OSOBA] PRIMARY KEY CLUSTERED
([ID] ASC))

CREATE TABLE [dbo].[MIEJSCE_PRACY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Opis] [nvarchar](50) NOT NULL,
CONSTRAINT [PK_MIEJSCE_PRACY] PRIMARY KEY CLUSTERED
(
[ID] ASC
))

ALTER TABLE [dbo].[AUX] ADD CONSTRAINT
[FK_AUX_OSOBA] FOREIGN KEY([ID_1])
REFERENCES [dbo].[OSOBA] ([ID])

ALTER TABLE [dbo].[AUX] CHECK CONSTRAINT
[FK_AUX_OSOBA]

ALTER TABLE [dbo].[AUX] ADD CONSTRAINT
[FK_AUX_MIEJSCE_PRACY] FOREIGN KEY([ID_2])
REFERENCES [dbo].[MIEJSCE_PRACY] ([ID])